#!/bin/bash


# faire le ntns pour le server
ip netns add server
# créer les switches
ovs-vsctl add-br resB
# configurer rout2
ip link add server-eth0 type veth peer name resB-server
ip link set server-eth0 netns server
ovs-vsctl add-port resB resB-server
ip link set dev resB-server up
ip netns exec server ip link set dev lo up
ip netns exec server ip link set dev server-eth0 up
ip link set resB up
ip address add 172.16.1.252/24 dev resB
ip netns exec server ip a add dev server-eth0 172.16.1.254/24
ip netns exec server ip a add dev server-eth0 3001:1030:5329:6d2c:211:deff:fead:beef/64
ip netns exec server ip r add default via 172.16.1.252
sysctl net.ipv4.conf.all.forwarding=1
